"YCM
nnoremap gd :YcmCompleter GoToDefinitionElseDeclaration
map <C-f>   :YcmCompleter GoToDefinitionElseDeclaration <CR>
imap <C-f>  :YcmCompleter GoToDefinitionElseDeclaration <CR>

" For C only
function! SwitchSourceHeader()
  "update!
  if (expand ("%:e") == "cpp")
    find %:t:r.h
  else
    find %:t:r.cpp
  endif
endfunction
nmap <C-g> :call SwitchSourceHeader()<CR>

" Switch splits
nmap <C-h> <C-W>h
nmap <C-j> <C-W>j
nmap <C-k> <C-W>k
nmap <C-l> <C-W>l

" Some hotkeys
nmap <F2>  :NERDTreeToggle<CR>
nmap <F12> :TagbarToggle<CR>
nmap <C-B> :Make<CR>
